CREATE PROCEDURE EliminarVenta
    @Id UNIQUEIDENTIFIER
AS
BEGIN
    SET NOCOUNT ON;
    BEGIN TRANSACTION
        DELETE FROM Ventas
        WHERE Id = @Id;
        SELECT @Id;
    COMMIT TRANSACTION
END