CREATE PROCEDURE EliminarPlatillo
    @Id UNIQUEIDENTIFIER
AS
BEGIN
    SET NOCOUNT ON;
    BEGIN TRANSACTION
        DELETE FROM Platillos
        WHERE Id = @Id;
        SELECT @Id;
    COMMIT TRANSACTION
END