CREATE PROCEDURE EliminarDetalleVenta
    @Id UNIQUEIDENTIFIER
AS
BEGIN
    SET NOCOUNT ON;
    BEGIN TRANSACTION
        DELETE FROM DetalleVenta
        WHERE Id = @Id;
        SELECT @Id;
    COMMIT TRANSACTION
END